### ISSUE TITLE
NullPointerException when using single Conjur instance to retrieve multiple secrets

### ISSUE THREAD

**Issue by derekjwashington** [cyberark/conjur-api-java#16]
When running the following test I receive the exception below. I am attempting to retrieve multiple secrets from a single Conjur instance. My goal is to inject a Conjur singleton into a class for parsing a config file that contains references to Conjur secrets.

`
    @Test
    public void getMultiple() {

        System.setProperty("CONJUR_ACCOUNT", "cloud");
        System.setProperty("CONJUR_AUTHN_LOGIN", "host/configuration-service");
        System.setProperty("CONJUR_AUTHN_API_KEY", "3c4gtv62qeprhbyedben2t4pa6s3jj5q8y12t356s3nzxtxg2vh8yrw");
        System.setProperty("CONJUR_APPLIANCE_URL", "http://localhost:8080");
        Conjur conjur = new Conjur();
        String username = conjur.variables().retrieveSecret("mongo/username");
//        conjur = new Conjur();
        String password = conjur.variables().retrieveSecret("mongo/password");
        System.out.format("%s/$s\n", username, password);
    }
` 

javax.ws.rs.ProcessingException: java.lang.NullPointerException

	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:544)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:526)
	at org.apache.cxf.jaxrs.client.WebClient.doResponse(WebClient.java:1093)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1052)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:854)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:825)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:393)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1567)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1487)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:81)
	at net.conjur.api.clients.ResourceClient.retrieveSecret(ResourceClient.java:30)
	at net.conjur.api.Variables.retrieveSecret(Variables.java:15)
	at com.insulet.cloud.config.ConjurTest.getValue(ConjurTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at org.joda.time.format.DateTimeFormatterBuilder$NumberFormatter.parseInto(DateTimeFormatterBuilder.java:1305)
	at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2516)
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:925)
	at net.conjur.api.Token.getTimestamp(Token.java:57)
	at net.conjur.api.Token.getExpiration(Token.java:65)
	at net.conjur.api.Token.willExpireWithin(Token.java:74)
	at net.conjur.util.rs.TokenAuthFilter.isTokenValid(TokenAuthFilter.java:35)
	at net.conjur.util.rs.TokenAuthFilter.filter(TokenAuthFilter.java:27)
	at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:60)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:611)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1051)
	... 31 more

**Comment by AndrewCopeland** [comment]
To resolve this issue `cxf-core-3.3.5.jar` must be a `Referenced Libraries`
