### ISSUE TITLE
Integration tests are failing but not reporting errors correctly

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-java#61]
Moved from #56 

The integration tests are experiencing failures, but are still showing as "successful" in the Jenkins pipeline

```
[2020-03-13T17:06:25.226Z] [[1;34mINFO[m] 
[2020-03-13T17:06:25.226Z] [[1;34mINFO[m] -------------------------------------------------------
[2020-03-13T17:06:25.226Z] [[1;34mINFO[m]  T E S T S
[2020-03-13T17:06:25.226Z] [[1;34mINFO[m] -------------------------------------------------------
[2020-03-13T17:06:25.485Z] [[1;34mINFO[m] Running net.conjur.api.[1mConjurTest[m
[2020-03-13T17:06:26.422Z] Mar 13, 2020 5:06:26 PM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLogging
[2020-03-13T17:06:26.422Z] WARNING: Interceptor for {https://cuke-master/secrets/cucumber/variable/test/testVariable}WebClient has thrown exception, unwinding now
[2020-03-13T17:06:26.422Z] javax.ws.rs.WebApplicationException: Error code: 401, Error message: 
[2020-03-13T17:06:26.422Z] 	at net.conjur.api.clients.AuthnClient.validateResponse(AuthnClient.java:85)
[2020-03-13T17:06:26.422Z] 	at net.conjur.api.clients.AuthnClient.authenticate(AuthnClient.java:48)
[2020-03-13T17:06:26.422Z] 	at net.conjur.util.rs.TokenAuthFilter.filter(TokenAuthFilter.java:28)
[2020-03-13T17:06:26.422Z] 	at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:60)
[2020-03-13T17:06:26.422Z] 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[2020-03-13T17:06:26.422Z] 	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:611)
[2020-03-13T17:06:26.422Z] 	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1051)
[2020-03-13T17:06:26.422Z] 	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:854)
[2020-03-13T17:06:26.423Z] 	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:825)
[2020-03-13T17:06:26.423Z] 	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:393)
[2020-03-13T17:06:26.423Z] 	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1567)
[2020-03-13T17:06:26.423Z] 	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1487)
[2020-03-13T17:06:26.423Z] 	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:81)
[2020-03-13T17:06:26.423Z] 	at net.conjur.api.clients.ResourceClient.retrieveSecret(ResourceClient.java:39)
[2020-03-13T17:06:26.423Z] 	at net.conjur.api.Variables.retrieveSecret(Variables.java:18)
[2020-03-13T17:06:26.423Z] 	at net.conjur.api.ConjurTest.testLogonWithAlterativeAuthenticator(ConjurTest.java:75)
[2020-03-13T17:06:26.423Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-13T17:06:26.423Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-13T17:06:26.423Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-13T17:06:26.423Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
[2020-03-13T17:06:26.423Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
[2020-03-13T17:06:26.423Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2020-03-13T17:06:26.423Z] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
[2020-03-13T17:06:26.423Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
[2020-03-13T17:06:26.423Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
[2020-03-13T17:06:26.423Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
[2020-03-13T17:06:26.423Z] 
[2020-03-13T17:06:26.682Z] [[1;34mINFO[m] [1;32mTests run: [0;1;32m4[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.162 s - in net.conjur.api.[1mConjurTest[m
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] 
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] Results:
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] 
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] [1;32mTests run: 4, Failures: 0, Errors: 0, Skipped: 0[m
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] 
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] Total time:  5.404 s
[2020-03-13T17:06:27.248Z] [[1;34mINFO[m] Finished at: 2020-03-13T17:06:26Z
```

AC:
- [ ] Update the integration tests so that they accurately report the test failures to Jenkins
- [ ] Update the integration tests to fix the failures

**Comment by JakeQuilty** [comment]
I think the exceptions that is being seen is being printed by the javax.ws.rs library. We are expecting an exception for a specific test and the tests are actually still passing its just the exception stack trace is being printed out as a warning. I'm will looking into suppressing this warning.

**Comment by sgnn7** [comment]
So I looked into this:
- I verified that this is not a test failure but is a legitimate expected failure scenario being tested.
- I tried to get the logging reduced but was unable to do so. Even if I was, there was a high chance that I could not isolate it to just this one test as the logging seems per-app and restructuring would be needed to make it per-client. 

Given that local testing is partially broken on latest version of OpenJDK (missing jaxb error classes; see [here](https://stackoverflow.com/a/43574427) for details) and the error is just informational from the JAXB code itself, I think we should leave this as-is unless we're doing deeper refactors of this API.

@izgeri / @JakeQuilty Closing for now but feel free to reopen if we still want this worked out.
